<ModalBody>
  <FormGroup>
    <label>
     Id:
    </label>

    <input
      className="form-control"
      readOnly
      type="text"
      value={this.state.form.id}
    />
  </FormGroup>

  <FormGroup>
    <label>
      Nombre:
    </label>
    <input
      className="form-control"
      name="Nombre"
      type="text"
      onChange={this.handleChange}
      value={this.state.form.Nombre}
    />
  </FormGroup>
  <FormGroup>
    <label>
      Apellido:
    </label>
    <input
      className="form-control"
      name="Apellido"
      type="text"
      onChange={this.handleChange}
      value={this.state.form.Apellido}
    />
  </FormGroup>
  <FormGroup>
    <label>
      Identificación:
    </label>
    <input
      className="form-control"
      name="Identificacion"
      type="text"
      onChange={this.handleChange}
      value={this.state.form.Identificacion}
    />
  </FormGroup>
  <FormGroup>
    <label>
      Rol:
    </label>
    <input
      className="form-control"
      name="Rol"
      type="text"
      onChange={this.handleChange}
      value={this.state.form.Rol}
    />
  </FormGroup>
  <FormGroup>
    <label>
      Estado:
    </label>
    <input
      className="form-control"
      name="Estado"
      type="text"
      onChange={this.handleChange}
      value={this.state.form.Estado}
    />
  </FormGroup>
  <FormGroup>
    <label>
      Teléfono:
    </label>
    <input
      className="form-control"
      type="text"
      name="Telefono"
      onChange={this.handleChange}
      value={this.state.form.Telefono}
    />
  </FormGroup>
  <FormGroup>
    <label>
    </label>
    Contraseña:
    <input
      className="form-control"
      name="Contraseña"
      type="text"
      onChange={this.handleChange}
      value={this.state.form.Contraseña}
    />
  </FormGroup>
  <FormGroup>
    <label>
    </label>
    email:
    <input
      className="form-control"
      name="email"
      type="text"
      onChange={this.handleChange}
      value={this.state.form.email}
    />
  </FormGroup>

</ModalBody>
